debug: false
spring:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.Oracle10gDialect
    open-in-view: true
    properties:
      hibernate:
        physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        auto_quote_keyword: true
        format_sql: true
  datasource:
    xepdb:
      jdbc-url: jdbc:oracle:thin:@//localhost:1521/XEPDB1
      username: GARY
      password: 1671123
      driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      minimumIdle: 5
      maximumPoolSize: 20
      idleTimeout: 30000
      maxLifetime: 2000000
      connectionTimeout: 30000
        
logging:
  level:
    root: INFO
    org.hibernate: ERROR
    org.hibernate.SQL: ERROR
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

server:
  port: 8081

jwt:
  secret: daf66e01593f61a15b857cf433aae03a005812b31234e149036bcc8dee755dbb
  expiration-ms: 600000