-- GARY.AUTH_USER definition
DROP TABLE "GARY"."AUTH_USER"; 
CREATE TABLE "GARY"."AUTH_USER" 
   (	"ID" LONG DEFAULT GARY.USER_ID_SEQ.NEXTVAL, 
	"USER_NO" VARCHAR2(30), 
	"USER_NAME" VARCHAR2(30), 
	"PASSWORD" VARCHAR2(30), 
	"EMAIL" VARCHAR2(50), 
	"STATUS" NUMBER(*,0) DEFAULT 1, 
	"LAST_LOGIN_DATE" DATE, 
	"LAST_CHG_PSW_DATE" DATE, 
	"PSW_EXPIRY_DAYS" NUMBER(*,0) DEFAULT 90, 
	"CREATE_DATE" DATE, 
	"UPDATE_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

COMMENT ON TABLE GARY.AUTH_USER IS '使用者資料';
COMMENT ON COLUMN GARY.AUTH_USER.STATUS IS '1:有效 2:無效 3:密碼過期';
COMMENT ON COLUMN GARY.AUTH_USER.LAST_CHG_PSW_DATE IS '上一次修改密碼時間';
COMMENT ON COLUMN GARY.AUTH_USER.PSW_EXPIRY_DAYS IS '密碼有效天數';

-- GARY.AUTH_GROUP definition
DROP TABLE "GARY"."AUTH_GROUP";
CREATE TABLE "GARY"."AUTH_GROUP" 
   (	"USER_NO" VARCHAR2(30), 
	"GROUP_NO" VARCHAR2(30)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;