-- GARY.AUTH_GROUP definition

CREATE TABLE "GARY"."AUTH_GROUP" 
   (	"ID" NUMBER(*,0) DEFAULT GARY.GROUP_ID_SEQ.NEXTVAL, 
	"GROUP_NAME" VARCHAR2(50), 
	"CREATE_USER" VARCHAR2(30), 
	"CREATE_DATE" DATE, 
	"UPDATE_USER" VARCHAR2(30), 
	"UPDATE_DATE" DATE, 
	"DESCRIPTION" VARCHAR2(100)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
  NO INMEMORY ("ID") ;


-- GARY.AUTH_USER definition

CREATE TABLE "GARY"."AUTH_USER" 
   (	"ID" NUMBER(*,0) DEFAULT GARY.USER_ID_SEQ.NEXTVAL, 
	"USER_NAME" VARCHAR2(30), 
	"PASSWORD" VARCHAR2(100), 
	"EMAIL" VARCHAR2(50), 
	"LAST_LOGIN_DATE" DATE, 
	"LAST_CHG_PSW_DATE" DATE, 
	"PSW_EXPIRY_DAYS" NUMBER(*,0) DEFAULT 90, 
	"ACCOUNT_EXPIRY_DAYS" NUMBER(*,0) DEFAULT 360, 
	"ENABLED" VARCHAR2(1) DEFAULT 'Y', 
	"LOCKED" VARCHAR2(1) DEFAULT 'N', 
	"CREATE_DATE" DATE, 
	"UPDATE_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

COMMENT ON TABLE GARY.AUTH_USER IS '使用者資料';
COMMENT ON COLUMN GARY.AUTH_USER.LAST_CHG_PSW_DATE IS '上一次修改密碼時間';
COMMENT ON COLUMN GARY.AUTH_USER.PSW_EXPIRY_DAYS IS '密碼有效天數';


-- GARY.AUTH_USER_GROUP definition

CREATE TABLE "GARY"."AUTH_USER_GROUP" 
   (	"USER_NAME" VARCHAR2(30), 
	"GROUP_NAME" VARCHAR2(50), 
	"CREATE_USER" VARCHAR2(30), 
	"CREATE_DATE" DATE, 
	"UPDATE_USER" VARCHAR2(30), 
	"UPDATE_DATE" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;